#!/usr/bin/env bash
set -e
# Make sure git is installed and we are in a git tree.
command -v git >/dev/null                       || { echo "UNKNOWN"; exit 0; }
git rev-parse --is-inside-work-tree &>/dev/null || { echo "UNKNOWN"; exit 0; }

TODAY=`date +%Y.%m.%d`

LATEST_VERSION_TAG=$(git describe --tags --match "v[0-9]*" --abbrev=0 `git rev-list --tags --max-count=1` 2>/dev/null || echo "")

if [ "$LATEST_VERSION_TAG" != "" ]; then
  VERSION_TAG_COMMIT=$(git rev-parse $LATEST_VERSION_TAG^{})
  CURRENT_COMMIT_NO=$(git rev-list --count HEAD ^$VERSION_TAG_COMMIT)
else
  CURRENT_COMMIT_NO=$(git rev-list --count HEAD)
fi

echo "$TODAY.$CURRENT_COMMIT_NO"
